### ISSUE TITLE
Adding percentages to two-way tables

### ISSUE THREAD

**Issue by MargheritaPhilipp** [IDEMSInternational/ParentAppDataScripts#26]
Could write in percentages for two-way tables function (as with multiple_summary_PT function) with the option of giving them by row or by column.

Row would be useful for e.g. gender (what percentage of Nontobeko users were male vs female)
Column could give info on share by organisation (e.g. what percentage of all users who have completed a workshop are from organisation x), but is probably less relevant.

**Comment by lilyclements** [comment]
Perhaps it would be good for us to go through implementing this together in a meeting.
We could have an hour working session again next week (perhaps Friday?) with @cabrinenyona (and anyone else interested - I'm afraid I'm not sure of Ester or Anastasia's github handles) to work on this. What do you think?

**Comment by cabrinenyona** [comment]
@lilyclements @Margherita-IDEMS  Adding percentages will be useful and implementing this in a working session will be more of a learning experience.  I was also thinking if adding mean ages will be useful as well in the near future, but we can discuss further.
